using sly.lexer;

namespace issue576;

public enum Issue576Lexer
{
    [Int]
    [Double]
    Number,
    [CustomId("_A-Za-z", "_0-9A-Za-z")]
    Identifier,
    [Lexeme(GenericToken.String)]
    [Lexeme(GenericToken.String, "'")]
    String,
    [Sugar("&")]
    BitwiseAnd,
    [Sugar("|")]
    BitwiseOr,
    [Sugar("^")]
    BitwiseXor,
    [Sugar("<<")]
    BitwiseLeftShift,
    [Sugar(">>")]
    BitwiseRightShift,
    [Sugar("~")]
    BitwiseNegation,
    [Sugar("+")]
    Addition,
    [Sugar("-")]
    Subtraction,
    [Sugar("*")]
    Multiplication,
    [Sugar("/")]
    Division,
    [Sugar("**")]
    Exponentiation,
    [Sugar("!")]
    Factorial,
    [Sugar("+=")]
    PlusEquals,
    [Sugar("-=")]
    MinusEquals,
    [Sugar("*=")]
    MultiplicationEquals,
    [Sugar("/=")]
    DivideEquals,
    [Sugar("**=")]
    PowerEquals,
    [Sugar("&=")]
    BitwiseAndEquals,
    [Sugar("|=")]
    BitwiseOrEquals,
    [Sugar("^=")]
    BitwiseXorEquals,
    [Sugar("<<=")]
    LeftShiftEquals,
    [Sugar(">>=")]
    RightShiftEquals,
    [Sugar("~=")]
    BitwiseNegateEquals,
    [Sugar("++")]
    Increment,
    [Sugar("--")]
    Decrement,
    [Keyword("and")]
    LogicalAnd,
    [Keyword("or")]
    LogicalOr,
    [Keyword("not")]
    LogicalNot,
    [Keyword("xor")]
    LogicalXor,
    [Keyword("implies")]
    LogicalImplies,
    [Sugar("(")]
    OpenParen,
    [Sugar(")")]
    CloseParen,
    [Sugar("{")]
    OpenCurly,
    [Sugar("}")]
    CloseCurly,
    [Sugar("[")]
    OpenSquare,
    [Sugar("]")]
    CloseSquare,
    [Sugar("<[")]
    OpenAngleSquare,
    [Sugar("]>")]
    CloseAngleSquare,
    [Sugar(",")]
    Comma,
    [Sugar(":")]
    Colon,
    [Sugar(".")]
    Dot,
    [Sugar("==")]
    EqualTo,
    [Sugar("!=")]
    NotEqualTo,
    [Sugar(">")]
    GreaterThan,
    [Sugar("<")]
    LessThan,
    [Sugar(">=")]
    GreaterThanOrEqualTo,
    [Sugar("<=")]
    LessThanOrEqualTo,
    [Keyword("is")]
    ComparisonIs,
    [Keyword("in")]
    In,
    [Sugar(";")]
    Semicolon,
    [Sugar("=")]
    Equals,
    [Keyword("float")]
    TypeFloat,
    [Keyword("int")]
    TypeInt,
    [Keyword("double")]
    TypeDouble,
    [Keyword("number")]
    [Keyword("bigfloat")]
    TypeNumber,
    [Keyword("long")]
    TypeLong,
    [Keyword("longint")]
    [Keyword("bigint")]
    TypeLongInt,
    [Keyword("byte")]
    TypeByte,
    [Keyword("array")]
    TypeArray,
    [Keyword("list")]
    TypeList,
    [Keyword("set")]
    TypeSet,
    [Keyword("dict")]
    TypeDict,
    [Keyword("short")]
    TypeShort,
    [Keyword("rational")]
    TypeRational,
    [Keyword("string")]
    TypeString,
    [Keyword("char")]
    TypeChar,
    [Keyword("void")]
    TypeVoid,
    [Keyword("bool")]
    TypeBool,
    [Keyword("return")]
    Return,
    [Keyword("break")]
    Break,
    [Keyword("continue")]
    Continue,
    [Keyword("if")]
    If,
    [Keyword("else")]
    Else,
    [Keyword("switch")]
    Switch,
    [Keyword("for")]
    For,
    [Keyword("while")]
    While,
    [Keyword("as")]
    As,
    [Keyword("cascading")]
    Cascading,
    [Keyword("copy")]
    Copy,
    [Keyword("readonly")]
    Readonly,
    [Keyword("frozen")]
    Frozen,
    [Keyword("immut")]
    Immut,
    [Keyword("ref")]
    Ref,
    [Keyword("new")]
    New,
    [Keyword("true")]
    TrueLiteral,
    [Keyword("false")]
    FalseLiteral,
    [Keyword("collection")]
    TypeCollection,
    [Keyword("pass")]
    Pass,
    [SingleLineComment("#")]
    [MultiLineComment("/*", "*/")]
    Comment,
}