<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>        
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

 

    <ItemGroup>
        <PackageReference Include="csly.generator" Version="0.9.6" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
