namespace com.stuffwithstuff.bantam {

    /**
     * A simple token class. These are generated by Lexer and consumed by Parser.
     */
    public class Token {
        public Token(TokenType type, string text) {
            mType = type;
            mText = text;
        }

        public TokenType getType() { return mType; }
        public string getText() { return mText; }

        public string toString() { return mText; }

        private TokenType mType;
        private string mText;
    }

}
