<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net7.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.12" />
    <PackageReference Include="sly" Version="3.5.3" />
    <PackageReference Include="System.Memory" Version="4.6.3" />    
  </ItemGroup>

  <ItemGroup>
    <None Remove="test.json" />
    <Content Include="test.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="BenchmarkDotNet.Artifacts\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BenchmarkDotNet.Artifacts\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="BenchmarkDotNet.Artifacts\**" />
  </ItemGroup>

</Project>
