<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>    
  </PropertyGroup>

  <ItemGroup>    
    <PackageReference Include="SharpCoreFileSystem" Version="1.1.6"/>
    <PackageReference Include="Sigil" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\while\while.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\sly\sly.csproj" OutputItemType="Analyzer"/>
  </ItemGroup>

  <ItemGroup>
    <None Remove="samples\counter.while" />
    <EmbeddedResource Include="samples\counter.while" />
    <None Remove="samples\factorial.while" />
    <EmbeddedResource Include="samples\factorial.while" />
    <None Remove="samples\fibo.while" />
    <EmbeddedResource Include="samples\fibonacci.while" />
    <None Remove="samples\simple.gram" />
    <EmbeddedResource Include="samples\simple.gram" />
    <None Remove="samples\while.gram" />
    <EmbeddedResource Include="samples\while.gram" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Remove="Generated\**\*.cs" />
    <None Include="Generated\**\*.cs" />
  </ItemGroup>
  
</Project>
